# Generated by Django 4.1.2 on 2022-10-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropyatchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaialbeBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_availabe_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('seat_number', models.IntegerField()),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropyatchapp.avaialbebooking')),
            ],
        ),
        migrations.AddField(
            model_name='avaialbebooking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropyatchapp.movie'),
        ),
        migrations.AddField(
            model_name='avaialbebooking',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropyatchapp.screen'),
        ),
    ]
