# Generated by Django 4.1.2 on 2022-10-16 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropyatchapp', '0002_avaialbebooking_movie_screen_booking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='screen',
            new_name='slot',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
